name: Propose tag to the tags-league
title: "Tag proposition: tagname"
description: "Propose a tag to be included in the 🏆tags-league"
labels: ["tag-proposition"]
assignees:
  - johannchopin
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in expanding the 🏆tags-league!
  - type: input
    id: tagName
    attributes:
      label: Name of the tag
      placeholder: ex. javascript
    validations:
      required: true
