## Description
<!-- 
Please do not leave this blank 
This PR [adds/removes/fixes/replaces] the [feature/bug/etc]. 
-->

## What type of PR is this? (check all applicable)

- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] ⚡️ Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Link to JIRA ticket(s)
<!-- Ex: https://buycoteam.atlassian.net/browse/FOO-42 -->

## Link to API ticket
<!-- If none please remove this section -->
- https://github.com/buyco/api/pull/42


## Screenshots
<!-- If none please remove this section -->


## Added tests?

- [ ] 👍 Yes
- [ ] 🙅 No, because they aren't needed
- [ ] 🙋 No, because I need help


## [optional] What gif best describes this PR or how it makes you feel? 😉

➡️ https://giphy.com/

